FROM ruby:2.6.2-alpine

# install need packages
RUN apk update && apk add \
    nodejs \
    postgresql-client \
    postgresql-dev \
    build-base \
    libffi-dev \
    git

# create working directory
WORKDIR /app

# add gem files
ADD ./server/Gemfile* /app/

# install gems
RUN gem install bundler
RUN bundle install --jobs 8

# set entrypoint
COPY ./docker/entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
