# stage1 - build react app first
FROM node:14-alpine as build

WORKDIR /app

COPY ./client /app

RUN yarn global add react-scripts
RUN yarn --silent
RUN yarn build


# stage 2 - build the final image and copy the react build files
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d

CMD ["nginx", "-g", "daemon off;"]
