FROM ruby:3.0.3-alpine3.13

# install need packages
RUN apk update && apk add \
    nodejs \
    postgresql-client \
    postgresql-dev \
    build-base \
    libffi-dev \
    git \
    tzdata \
    shared-mime-info

# create working directory
WORKDIR /app

# add gem files
COPY ./server/Gemfile* /
RUN gem install bundler
RUN bundle install --jobs 8

# set entrypoint
COPY ./docker/*.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
